version: '3.8'
services:
  paceme-functionapp:
    container_name: paceme-functionapp
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - PaceMeStorageAccount=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://paceme-storage:10002/devstoreaccount1;
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - AzureWebJobsStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://paceme-function-storage;
      - OpenIdConfig
      - ValidAudience
      - ValidIssuer
    volumes:
      - ../:/workspaces/PaceMe.API:cached
      - type: bind
        source: ~/.ssh
        target: /home/vscode/.ssh

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - '7071:7071'
    command: /bin/sh -c "while sleep 1000; do :; done"
  paceme-function-storage:
    container_name: paceme-function-storage
    image: mcr.microsoft.com/azure-storage/azurite
    ports: 
      - '10000:10000'
      - '10001:10001'
  paceme-storage:
    container_name: paceme-storage
    build:
      context: .
      dockerfile: tablestorage.Dockerfile
    tty: true
    restart: always
    ports:
        - "10002:10002" #table